SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[ListarVentas]
AS
SELECT CLIENTE.IDCLI, CLIENTE.NOMCLI, EMPLEADO.IDEMP, EMPLEADO.NOMEMP, PRODUCTO.IDPRO, PRODUCTO.TIPPRO, VENTAS.IDVEN, VENTAS.FECVEN, VENTAS.PREVEN, VENTAS.ESTVEN FROM VENTAS
INNER JOIN CLIENTE ON CLIENTE.IDCLI = VENTAS.IDCLI
INNER JOIN EMPLEADO ON EMPLEADO.IDEMP = VENTAS.IDEMP
INNER JOIN PRODUCTO ON PRODUCTO.IDPRO = PRODUCTO.IDPRO WHERE VENTAS.ESTVEN = 'A' 
GO
