SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[ListarClientes]
AS
SELECT CLIENTE.IDCLI, SUCURSAL.IDSUC, SUCURSAL.DISSUC, CLIENTE.DIRCLI, CLIENTE.NOMCLI, 
CLIENTE.APECLI, CLIENTE.CELCLI, CLIENTE.ESTCLI FROM CLIENTE
INNER JOIN SUCURSAL ON SUCURSAL.IDSUC = CLIENTE.IDSUC WHERE CLIENTE.ESTCLI = 'A'
GO
