SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[ListarHistorial]
AS
SELECT HISTORIAL_VENTAS.IDINV, HISTORIAL_VENTAS.FECINV, HISTORIAL_VENTAS.ESTINV, EMPLEADO.IDEMP, EMPLEADO.NOMEMP, VENTAS.IDVEN, VENTAS.PREVEN FROM HISTORIAL_VENTAS
INNER JOIN EMPLEADO ON EMPLEADO.IDEMP = HISTORIAL_VENTAS.IDEMP
INNER JOIN VENTAS ON VENTAS.IDVEN = HISTORIAL_VENTAS.IDVEN WHERE HISTORIAL_VENTAS.ESTINV = 'A'
GO
