SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- REGISTRAR CLIENTE
CREATE PROCEDURE [dbo].[RegistrarCliente]
@NOMBRES VARCHAR(100),
@APELLIDO VARCHAR (20),
@CELULAR CHAR (9),
@ESTADO CHAR(1)
AS
INSERT INTO CLIENTE (NOMCLI,APECLI,CELCLI,ESTCLI)
VALUES(@NOMBRES,@APELLIDO,@CELULAR,@ESTADO)
GO
