SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[RegristrarVentas]
@FECHA DATE,
@PRECIO MONEY,
@ESTADO CHAR(1)
AS
INSERT INTO VENTAS (FECVEN, PREVEN, ESTVEN)
VALUES(@FECHA, @PRECIO, @ESTADO)

GO
