SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RegistrarEmpleado]
@NOMBRE VARCHAR(30),
@APELLIDOS VARCHAR(20),
@CELULAR CHAR(9),
@DNI CHAR(8),
@SEXO CHAR(1),
@TIPO CHAR(1),
@ESTADO CHAR(1)
AS
INSERT INTO EMPLEADO (NOMEMP, APEPATEMP, CELEMP, DNIEMP, SEXEMP, TIPEMP , ESTEMP)
VALUES(@NOMBRE, @APELLIDOS,@CELULAR,@DNI,@SEXO,@TIPO,@ESTADO)
GO
