CREATE TABLE [dbo].[EMPLEADO]
(
[IDEMP] [int] NOT NULL IDENTITY(1, 1),
[IDSUC] [int] NOT NULL,
[NOMEMP] [varchar] (25) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEPATEMP] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEMATEMP] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CELEMP] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIEMP] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[SEXEMP] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TIPEMP] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTEMP] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADO] ADD CONSTRAINT [EMPLEADO_pk] PRIMARY KEY CLUSTERED  ([IDEMP]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADO] ADD CONSTRAINT [EMPLEADO_SUCURSAL] FOREIGN KEY ([IDSUC]) REFERENCES [dbo].[SUCURSAL] ([IDSUC])
GO
