CREATE TABLE [dbo].[HISTORIAL_VENTAS]
(
[IDINV] [int] NOT NULL IDENTITY(1, 1),
[IDEMP] [int] NOT NULL,
[IDVEN] [int] NOT NULL,
[FECINV] [date] NOT NULL,
[ESTINV] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORIAL_VENTAS] ADD CONSTRAINT [HISTORIAL_VENTAS_pk] PRIMARY KEY CLUSTERED  ([IDINV]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORIAL_VENTAS] ADD CONSTRAINT [INVENTARIO_EMPLEADO] FOREIGN KEY ([IDEMP]) REFERENCES [dbo].[EMPLEADO] ([IDEMP])
GO
