CREATE TABLE [dbo].[VENTAS]
(
[IDVEN] [int] NOT NULL IDENTITY(1, 1),
[IDCLI] [int] NOT NULL,
[IDEMP] [int] NOT NULL,
[IDPRO] [int] NOT NULL,
[FECVEN] [date] NOT NULL,
[PREVEN] [money] NOT NULL,
[ESTVEN] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTAS] ADD CONSTRAINT [VENTAS_pk] PRIMARY KEY CLUSTERED  ([IDVEN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTAS] ADD CONSTRAINT [VENTAS_CLIENTE] FOREIGN KEY ([IDCLI]) REFERENCES [dbo].[CLIENTE] ([IDCLI])
GO
ALTER TABLE [dbo].[VENTAS] ADD CONSTRAINT [VENTAS_VENDEDOR] FOREIGN KEY ([IDEMP]) REFERENCES [dbo].[EMPLEADO] ([IDEMP])
go
