CREATE TABLE [dbo].[SUCURSAL]
(
[IDSUC] [int] NOT NULL IDENTITY(1, 1),
[DISSUC] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTSUC] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUCURSAL] ADD CONSTRAINT [SUCURSAL_pk] PRIMARY KEY CLUSTERED  ([IDSUC]) ON [PRIMARY]
GO
